# Single service deployment example
# Usage: helm install my-microservice ./chart/ -f values-single.yaml

# Global chart configuration
# nameOverride: Override chart name in resource names (e.g., "proxy" -> my-app-proxy-microservice)
nameOverride: ""
# fullnameOverride: Complete control over base name (e.g., "my-service" -> my-service-microservice)
fullnameOverride: ""
# imagePullSecrets: Secrets for private registries
imagePullSecrets: []

# Default values for all services
defaults:
  replicaCount: 1

  image:
    repository: ghcr.io/liamawhite/microservice
    pullPolicy: IfNotPresent
    tag: "latest"

  serviceAccount:
    create: true
    automount: true
    name: ""



  securityContext: {}

  service:
    type: ClusterIP
    port: 8080

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5





  config:
    serviceName: "microservice"
    port: 8080
    timeout: "30s"
    logLevel: "info"
    logFormat: "json"

# Single service configuration
services:
  - name: "microservice"
    # Uses all defaults - no overrides needed