{{- $effectiveServices := include "microservice.effectiveServices" . | fromYaml -}}
{{- $createdServiceAccounts := list -}}
{{- range $effectiveServices }}
{{- $service := . -}}
{{- $serviceConfig := include "microservice.getServiceConfig" (dict "service" $service "root" $) | fromYaml -}}
{{- if $serviceConfig.serviceAccount.create }}
{{- $serviceAccountName := include "microservice.serviceAccountNameForService" (dict "service" $service "root" $) -}}
{{- if not (has $serviceAccountName $createdServiceAccounts) }}
{{- $createdServiceAccounts = append $createdServiceAccounts $serviceAccountName -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  labels:
    {{- include "microservice.serviceLabels" (dict "service" $service "root" $) | nindent 4 }}
  {{- with $serviceConfig.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $serviceConfig.serviceAccount.automount }}
{{- end }}
{{- end }}
{{- end }}