{{- $createdServiceAccounts := list -}}
{{- range .Values.services }}
{{- $service := . -}}
{{- $serviceConfig := include "microservice.getServiceConfig" (dict "service" $service "root" $) | fromYaml -}}
{{- if $serviceConfig.serviceAccount.create }}
{{- $serviceAccountName := include "microservice.serviceAccountNameForService" (dict "service" $service "root" $) -}}
{{- if not (has $serviceAccountName $createdServiceAccounts) }}
{{- $createdServiceAccounts = append $createdServiceAccounts $serviceAccountName -}}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  {{- with $.Values.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "microservice.serviceLabels" (dict "service" $service "root" $) | nindent 4 }}
automountServiceAccountToken: {{ $serviceConfig.serviceAccount.automount }}
---
{{- end }}
{{- end }}
{{- end }}
