{{- range .Values.services }}
{{- $service := . -}}
{{- $serviceConfig := include "microservice.getServiceConfig" (dict "service" $service "root" $) | fromYaml -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.serviceName" (dict "service" $service "root" $) }}
  {{- with $.Values.namespace.name }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "microservice.serviceLabels" (dict "service" $service "root" $) | nindent 4 }}
spec:
  type: {{ $serviceConfig.service.type }}
  ports:
    - port: {{ $serviceConfig.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "microservice.serviceSelectorLabels" (dict "service" $service "root" $) | nindent 4 }}
---
{{- end }}
