name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ghcr:
    name: ghcr.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push multi-platform image
      run: |
        DOCKER_TAG=${{ github.sha }} DOCKER_PUSH=true make docker-build
        DOCKER_TAG=latest DOCKER_PUSH=true make docker-build

    - name: Package and push Helm chart
      run: |
        HELM_VERSION=${{ github.sha }} HELM_APP_VERSION=${{ github.sha }} make helm-push
        HELM_VERSION=latest HELM_APP_VERSION=latest make helm-push